apiVersion: v1
kind: Namespace
metadata:
  name: node-app-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: node-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: senpiyan/node-sample-app:latest
        imagePullPolicy: Always
        name: nodeapp
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1024m
            memory: 1Gi
          requests:
            cpu: 512m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: node-app-ns
  name: nodeappservice
  labels:
    app: nodeapp
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: nodeapp

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nodeappservice
  namespace: node-app-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nodeapp.flame.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nodeappservice
          servicePort: 3000